<a href="https://colab.research.google.com/github/anuanu0-0/Deep-Learning/blob/master/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Simple data types and operators


In [10]:
name = 'Hello World'
type(name)


str

In [11]:
print(name)

Hello World


In [12]:
size = 12.22
type(size)

float

In [13]:
num = 2
type(num)

int

In [14]:
print('Its just a ' + name + ' program')

Its just a Hello World program


In [15]:
a = 1
b = 6
print(a*b, a/b, a+b, a-b, a**b, a//b)

6 0.16666666666666666 7 -5 1 0


In [16]:
is_android = False
type(is_android)


bool

In [17]:
print (is_android == True and num > 1)
print (is_android == True or num > 1)

False
True


# Blocks -If, For, While


In [18]:
if is_android == True:
  print('Hello there')
  # Try to make is_android = true while declaration
print ('I always run') 

I always run


In [19]:
for i in range(2, 5):
  print (i, i**2)

2 4
3 9
4 16


In [0]:
range?


In [21]:
i = 0
while i < 5:
  print (i, i**2)
  i += 1

0 0
1 1
2 4
3 9
4 16


# Functions


In [0]:
def print_square(stop_val):
  for i in range(stop_val):
    print (i, i**2)

In [23]:
print_square(5)

0 0
1 1
2 4
3 9
4 16


In [0]:

def print_square_sum(stop_val):
  sum_ = 0
  for i in range(stop_val):
    sum_ += i ** 2
  return sum_

In [25]:
print_square_sum(5)

30

In [0]:
def print_squares_with_startval(stop_val , start_val = 0):
    for i in range(start_val, stop_val):
      print (i , i**2)

In [27]:
print_squares_with_startval(4, 2)

2 4
3 9


In [0]:
print_squares_with_startval?

# Lists


In [29]:
my_life = [name, is_android, size]
print (my_life)

['Hello World', False, 12.22]


In [30]:
type(my_life)

list

In [31]:
my_life[2]

12.22

In [32]:
my_life[1:3]

[False, 12.22]

In [0]:
my_other_life = my_life
my_secondOther_life = list(my_life)

In [34]:
print (my_other_life)
print (my_secondOther_life)

['Hello World', False, 12.22]
['Hello World', False, 12.22]


In [35]:
my_life[2] = 1001.1001
print (my_life)

['Hello World', False, 1001.1001]


In [36]:
len (my_life)

3

In [0]:
len?

In [38]:
my_life.append('Coding')
print (my_life)

['Hello World', False, 1001.1001, 'Coding']


In [39]:
pro = ['backtracking', 101]
my_life = my_life + pro
print (my_life)

['Hello World', False, 1001.1001, 'Coding', 'backtracking', 101]


In [40]:
for data in my_life:
  print (data)

Hello World
False
1001.1001
Coding
backtracking
101


In [41]:
range(5)

range(0, 5)

In [42]:
print (list(range(5)))

[0, 1, 2, 3, 4]


In [43]:
a = list(range(5))
print (a)

[0, 1, 2, 3, 4]


In [0]:
map?

In [45]:
z = [1,2,3,4,5]
test = list(map(lambda x: x * 2, z))
print(test)

[2, 4, 6, 8, 10]


In [46]:
b = list(map(lambda x: x**2, a))
print (b)

[0, 1, 4, 9, 16]


In [47]:
c = list(filter(lambda x: x % 2 != 0, b))
print(c)

[1, 9]


# Tuples, Sets and Dicts

In [48]:
my_work_tuple = ('StartUp', True, 11.54)
print(my_work_tuple)
type (my_work_tuple)

('StartUp', True, 11.54)


tuple

In [49]:
my_work_tuple[1:3]

(True, 11.54)

In [50]:
for data in my_work_tuple:
  print(data)

StartUp
True
11.54


In [51]:
my_work_tuple[2] = 1

TypeError: ignored

In [0]:
import time
tic = time.time()
print(tic)

In [0]:
time.time?

In [0]:
tic = time.time()
# Time elapsed in this comment is the difference between tic and toc
toc = time.time()
print('Elapsed time' , toc - tic)

In [0]:
my_list = list(range(1000000))
tic = time.time()
my_list_squared = map(lambda i: i**2, my_list)
toc = time.time()
print('Elapsed time in sec' , toc - tic)

In [0]:
my_tuple = tuple(range(1000000))
tic = time.time()
my_tuple_squared = map(lambda i: i**2, my_tuple)
toc = time.time()
print('Elapsed time in sec' , toc - tic)
# Time taken in a tuple manipulation is less than the list manipulation


In [0]:
my_set = set(my_life)
print(my_set)

In [0]:
my_list = list(range(1000000))
tic = time.time()
print (98731 in my_list)
print (131581 in my_list)
print (111111111111111 in my_list)
toc = time.time()
print('Elapsed time in sec' , toc - tic)

In [0]:
my_set = set(range(1000000))
tic = time.time()
print (98731 in my_list)
print (131581 in my_list)
print (111111111111111 in my_list)
toc = time.time()
print('Elapsed time in sec' , toc - tic)

In [0]:
my_work_dict = {}
type (my_work_dict)

In [0]:
my_work_dict['name'] = 'coding'
my_work_dict['isActive'] = True
my_work_dict['timeStamp'] =  12.19
print(my_work_dict)

In [0]:
my_work_dict['name']

In [0]:
print(my_work_dict.keys())
print (my_work_dict.values())
print(my_work_dict.items())

In [0]:
for key in my_work_dict.keys():
  print(key, ':', my_work_dict[key])

# Python Packages



In [0]:
import math 
a = math.sqrt(100)
print(a)

In [0]:
a = math.pow(100, 0.5)
print(a)

In [0]:
x = 100
y = 1
for i in range(1, x):
  y *= i
print('Factorial of', x, 'is', y)

In [0]:
y = math.factorial(x)

In [0]:
import math as m 
y = m.factorial(x)

In [0]:
from math import factorial
y = factorial(x)

In [0]:
val = list(range(1, 5))
tic = time.time()
y = 1
for x in val:
  y *= x
  print (y) 
  toc = time.time()
print('Elapsed time is ' , toc - tic) 
tic = time.time()
# See the difference in time intervals
for x in val:  
  y1 = math.factorial(x)  
  print(y1)
  toc = time.time()
print('Elapsed time is ' , toc - tic) 


In [0]:
!echo 'def hello():' > my_first_module.py
!echo '    print("Hello there.  It is another file")' >> my_first_module.py
!cat my_first_module.py

In [0]:
import my_first_module
my_first_module.hello()

In [0]:
from my_first_module import hello
hello()

# File Handling

In [0]:
!wget https://drive.google.com/drive/u/0/folders/1lDUKRkmRvtgMw2ihD8VZzT2ju8tjM6iN

In [0]:
!ls


In [0]:
!wget /content/sample_data/california_housing_test.csv

In [0]:
!ls

In [0]:
file = open('california_housing_test.csv', 'r')

In [0]:
s = file.readline()

In [0]:
!wget https://drive.google.com/drive/u/0/folders/1lDUKRkmRvtgMw2ihD8VZzT2ju8tjM6iN

# Python Classes

In [0]:
"""class Test:
  def __init__(self, name, is_work = False, size = 4.3 ):
    self.name = name
    self
    """

# NumPy

In [52]:
import numpy as np
X = np.array([1, 2, 3])
print (X)

[1 2 3]


In [53]:
type(X)

numpy.ndarray

In [64]:
L = [400, 510, 6]
X = np.asarray(L)
type(X)

numpy.ndarray

In [65]:
print(X)

[400 510   6]


In [0]:
np.asarray?

In [73]:
X = np.asarray(L, dtype=float )
print(X)

[400. 510.   6.]


In [68]:
X.shape

(3,)

In [0]:
X.shape?


In [0]:
np.array?

In [78]:
X = np.array([[0,1,2,3],[1,4,5,6], [2,7,8,9]])
print(X)
X.shape

[[0 1 2 3]
 [1 4 5 6]
 [2 7 8 9]]


(3, 4)

In [81]:
X[1,2]+X[2,0]

7

In [84]:
X[0, 0:2]

array([0, 1])

In [85]:
X[1, 0:2]

array([1, 4])

In [87]:
X[0,:]

array([0, 1, 2, 3])

In [88]:
X[0:]

array([[0, 1, 2, 3],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [90]:
X[:3]

array([[0, 1, 2, 3],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [93]:
X = np.zeros((4,5))
print(X)
np.zeros?

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [94]:
X = np.eye(4,4)
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [102]:
X = np.random.random((4,5))
print(X)

[[0.91066904 0.82516717 0.33492069 0.56548885 0.48344172]
 [0.99497585 0.22372263 0.49784931 0.24991025 0.91031483]
 [0.47593711 0.08546765 0.48784159 0.257908   0.19899508]
 [0.36265969 0.70636082 0.63210512 0.8398629  0.95187073]]
