<a href="https://colab.research.google.com/github/anuanu0-0/Deep-Learning/blob/master/Getting-Started/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Simple data types and operators


In [0]:
name = 'Hello World'
type(name)


str

In [0]:
print(name)

Hello World


In [0]:
size = 12.22
type(size)

float

In [0]:
num = 2
type(num)

int

In [0]:
print('Its just a ' + name + ' program')

Its just a Hello World program


In [0]:
a = 1
b = 6
print(a*b, a/b, a+b, a-b, a**b, a//b)

6 0.16666666666666666 7 -5 1 0


In [0]:
is_android = False
type(is_android)


bool

In [0]:
print (is_android == True and num > 1)
print (is_android == True or num > 1)

False
True


# Blocks -If, For, While


In [0]:
if is_android == True:
  print('Hello there')
  # Try to make is_android = true while declaration
print ('I always run') 

I always run


In [0]:
for i in range(2, 5):
  print (i, i**2)

2 4
3 9
4 16


In [0]:
range?


In [0]:
i = 0
while i < 5:
  print (i, i**2)
  i += 1

0 0
1 1
2 4
3 9
4 16


# Functions


In [0]:
def print_square(stop_val):
  for i in range(stop_val):
    print (i, i**2)

In [0]:
print_square(5)

0 0
1 1
2 4
3 9
4 16


In [0]:

def print_square_sum(stop_val):
  sum_ = 0
  for i in range(stop_val):
    sum_ += i ** 2
  return sum_

In [0]:
print_square_sum(5)

30

In [0]:
def print_squares_with_startval(stop_val , start_val = 0):
    for i in range(start_val, stop_val):
      print (i , i**2)

In [0]:
print_squares_with_startval(4, 2)

2 4
3 9


In [0]:
print_squares_with_startval?

# Lists


In [0]:
my_life = [name, is_android, size]
print (my_life)

['Hello World', False, 12.22]


In [0]:
type(my_life)

list

In [0]:
my_life[2]

12.22

In [0]:
my_life[1:3]

[False, 12.22]

In [0]:
my_other_life = my_life
my_secondOther_life = list(my_life)

In [0]:
print (my_other_life)
print (my_secondOther_life)

['Hello World', False, 12.22]
['Hello World', False, 12.22]


In [0]:
my_life[2] = 1001.1001
print (my_life)

['Hello World', False, 1001.1001]


In [0]:
len (my_life)

3

In [0]:
len?

In [0]:
my_life.append('Coding')
print (my_life)

['Hello World', False, 1001.1001, 'Coding']


In [0]:
pro = ['backtracking', 101]
my_life = my_life + pro
print (my_life)

['Hello World', False, 1001.1001, 'Coding', 'backtracking', 101]


In [0]:
for data in my_life:
  print (data)

Hello World
False
1001.1001
Coding
backtracking
101


In [0]:
range(5)

range(0, 5)

In [0]:
print (list(range(5)))

[0, 1, 2, 3, 4]


In [0]:
a = list(range(5))
print (a)

[0, 1, 2, 3, 4]


In [0]:
map?

In [0]:
z = [1,2,3,4,5]
test = list(map(lambda x: x * 2, z))
print(test)

[2, 4, 6, 8, 10]


In [0]:
b = list(map(lambda x: x**2, a))
print (b)

[0, 1, 4, 9, 16]


In [0]:
c = list(filter(lambda x: x % 2 != 0, b))
print(c)

[1, 9]


# Tuples, Sets and Dicts

In [0]:
my_work_tuple = ('StartUp', True, 11.54)
print(my_work_tuple)
type (my_work_tuple)

('StartUp', True, 11.54)


tuple

In [0]:
my_work_tuple[1:3]

(True, 11.54)

In [0]:
for data in my_work_tuple:
  print(data)

StartUp
True
11.54


In [0]:
my_work_tuple[2] = 1

TypeError: ignored

In [0]:
import time
tic = time.time()
print(tic)

In [0]:
time.time?

In [0]:
tic = time.time()
# Time elapsed in this comment is the difference between tic and toc
toc = time.time()
print('Elapsed time' , toc - tic)

In [0]:
my_list = list(range(1000000))
tic = time.time()
my_list_squared = map(lambda i: i**2, my_list)
toc = time.time()
print('Elapsed time in sec' , toc - tic)

In [0]:
my_tuple = tuple(range(1000000))
tic = time.time()
my_tuple_squared = map(lambda i: i**2, my_tuple)
toc = time.time()
print('Elapsed time in sec' , toc - tic)
# Time taken in a tuple manipulation is less than the list manipulation


In [0]:
my_set = set(my_life)
print(my_set)

In [0]:
my_list = list(range(1000000))
tic = time.time()
print (98731 in my_list)
print (131581 in my_list)
print (111111111111111 in my_list)
toc = time.time()
print('Elapsed time in sec' , toc - tic)

In [0]:
my_set = set(range(1000000))
tic = time.time()
print (98731 in my_list)
print (131581 in my_list)
print (111111111111111 in my_list)
toc = time.time()
print('Elapsed time in sec' , toc - tic)

In [0]:
my_work_dict = {}
type (my_work_dict)

In [0]:
my_work_dict['name'] = 'coding'
my_work_dict['isActive'] = True
my_work_dict['timeStamp'] =  12.19
print(my_work_dict)

In [0]:
my_work_dict['name']

In [0]:
print(my_work_dict.keys())
print (my_work_dict.values())
print(my_work_dict.items())

In [0]:
for key in my_work_dict.keys():
  print(key, ':', my_work_dict[key])

# Python Packages



In [0]:
import math 
a = math.sqrt(100)
print(a)

In [0]:
a = math.pow(100, 0.5)
print(a)

In [0]:
x = 100
y = 1
for i in range(1, x):
  y *= i
print('Factorial of', x, 'is', y)

In [0]:
y = math.factorial(x)

In [0]:
import math as m 
y = m.factorial(x)

In [0]:
from math import factorial
y = factorial(x)

In [0]:
val = list(range(1, 5))
tic = time.time()
y = 1
for x in val:
  y *= x
  print (y) 
  toc = time.time()
print('Elapsed time is ' , toc - tic) 
tic = time.time()
# See the difference in time intervals
for x in val:  
  y1 = math.factorial(x)  
  print(y1)
  toc = time.time()
print('Elapsed time is ' , toc - tic) 


In [0]:
!echo 'def hello():' > my_first_module.py
!echo '    print("Hello there.  It is another file")' >> my_first_module.py
!cat my_first_module.py

In [0]:
import my_first_module
my_first_module.hello()

In [0]:
from my_first_module import hello
hello()

# File Handling

In [0]:
!wget https://www.dropbox.com/s/w94odi4aq1k44lf/mobile_cleaned.csv

In [0]:
!wget https://onedrive.live.com/Edit.aspx?resid=A5151AA767C7DC0D!11701&wd=cpe

In [0]:
!ls

In [0]:
file = open('mobile_cleaned.csv', 'r')

In [0]:
s = file.readline()

In [0]:
print(s)

In [0]:
print(s.split(','))

In [0]:
file.close()

In [0]:
file.readline()

In [0]:
with open('mobile_cleaned.csv','r') as file:
  print (file.readline())

In [0]:
with open('mobile_cleaned.csv') as file:
  print(file.read())

In [0]:
with open('mobile_cleaned.csv', 'r') as file:
  for line in file:
    for word in line.split(','):
      print(word)
    print('--------')  

In [0]:
with open('my_first_file_output.txt', 'w') as file:
  file.write('Hello worldfrom python code')

In [0]:
!cat my_first_file_output.txt

# Python Classes

In [0]:
class Test:
  """This is a sample class to illustrate how python classes work"""
  def __init__(self, name, is_work = False, size = 4.3 ):
    self.name = name
    self.is_work = is_work
    self.size = size
    self.rating = -1

  def has_rating(self) :
    return self.rating > -1
    
  

In [0]:
new_life = Test('Coding')
type(new_life)

In [0]:
print(new_life.name, new_life.is_work, new_life.size)

In [0]:
new_life.size = 0

In [0]:
new_life.has_rating()

In [0]:
new_life.rating = 101

In [0]:
new_life.has_rating()

In [0]:
Test.__doc__

In [0]:
class Play(Test):
  def __init__(self, name):
    Test.__init__(self, name, False, 4)

  def __str__(self):
    return self.name + " " + str(self.is_work) + " " +str(self.size)    

In [0]:
new_Life = Play('Code')
new_Life.is_work

# NumPy

In [0]:
import numpy as np
X = np.array([1, 2, 3])
print (X)

[1 2 3]


In [0]:
type(X)

numpy.ndarray

In [0]:
L = [400, 510, 6]
X = np.asarray(L)
type(X)


numpy.ndarray

In [0]:
print(X)

[400 510   6]


In [0]:
np.asarray?

In [0]:
X = np.asarray(L, dtype=float )
print(X)

[400. 510.   6.]


In [0]:
X.shape

(3,)

In [0]:
X.shape?


In [0]:
np.array?

In [0]:
X = np.array([[0,1,2,3],[1,4,5,6], [2,7,8,9]])
print(X)
X.shape

[[0 1 2 3]
 [1 4 5 6]
 [2 7 8 9]]


(3, 4)

In [0]:
X[1,2]+X[2,0]

7

In [0]:
X[0, 0:2]

array([0, 1])

In [0]:
X[1, 0:2]

array([1, 4])

In [0]:
X[0,:]

array([0, 1, 2, 3])

In [0]:
X[0:]

array([[0, 1, 2, 3],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [0]:
X[:3]

array([[0, 1, 2, 3],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [0]:
X = np.zeros((4,5))
print(X)
# np.zeros?

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
X = np.eye(4,4)
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
X = np.random.random((4,5))
print(X)

[[0.10164559 0.76230083 0.12252071 0.48014589 0.1703636 ]
 [0.6068754  0.43070082 0.92302058 0.73746276 0.82238765]
 [0.28152666 0.79479663 0.53265091 0.70466053 0.42127354]
 [0.23272573 0.00240298 0.87292811 0.12435509 0.83357477]]


In [0]:
Z = X.T
print(Z)

[[0.10164559 0.6068754  0.28152666 0.23272573]
 [0.76230083 0.43070082 0.79479663 0.00240298]
 [0.12252071 0.92302058 0.53265091 0.87292811]
 [0.48014589 0.73746276 0.70466053 0.12435509]
 [0.1703636  0.82238765 0.42127354 0.83357477]]


In [0]:
Y = X.reshape(20, 1)
print(Y)

[[0.10164559]
 [0.76230083]
 [0.12252071]
 [0.48014589]
 [0.1703636 ]
 [0.6068754 ]
 [0.43070082]
 [0.92302058]
 [0.73746276]
 [0.82238765]
 [0.28152666]
 [0.79479663]
 [0.53265091]
 [0.70466053]
 [0.42127354]
 [0.23272573]
 [0.00240298]
 [0.87292811]
 [0.12435509]
 [0.83357477]]


In [0]:
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [0]:
B = np.arange(5)

In [0]:
C = A + B
D = A - B
E = A * B
print (C, D, E)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [0]:
print(A, A + 1)

[0 1 2 3 4] [1 2 3 4 5]


In [0]:
A = np.random.random((2, 3))
print (A)
print (A + 1)

[[0.41901376 0.30802462 0.02685475]
 [0.99706848 0.49809028 0.50008813]]
[[1.41901376 1.30802462 1.02685475]
 [1.99706848 1.49809028 1.50008813]]


In [0]:
A = np.floor(np.random.random((2, 3)) * 10)
print (A)

[[3. 3. 4.]
 [3. 4. 2.]]


In [0]:
u = [1, 2, 3]
v = [-1, 0, 1]
p1 = np.inner(u, v)
print (p1)

2


In [0]:
p2 = np.outer(u, v)
print (p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [79]:
A = np.ones((2,3))
B = np.ones((3,2))
print (A)
print (B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [80]:
np.dot(A, B)

array([[3., 3.],
       [3., 3.]])

In [0]:
np.dot?

In [0]:
np.inner?

In [83]:
np.dot(B.T, A.T)

array([[3., 3.],
       [3., 3.]])

In [84]:
A = np.ones((2, 3))
print (A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [85]:
A.sum()

6.0

In [86]:
A.sum(axis = 0)

array([2., 2., 2.])

In [87]:
A.sum(axis = 1)

array([3., 3.])

In [88]:
A.sum(axis = 3)

AxisError: ignored

In [89]:
A.max()

1.0

# Plotting